### ISSUE TITLE
Use GPIOSystem for Buzzer

### ISSUE THREAD

**Issue by camsaway** [chiefwigms/GPIOSystem#1]
Hi,
How would I go about using GPIOSystem for the buzzer activation in CBPi? For whatever reason I can't get CraftBeerPi to access my GPIOs with the normal actor types, but they work fine with this plug-in.
Not having alerts is annoying (and I would prefer not to add a specific buzzer step).
Cheers,
Cameron.

**Comment by chiefwigms** [comment]
You'll probably have to modify https://github.com/Manuel83/craftbeerpi3/blob/master/modules/buzzer/__init__.py
for use with the plugin.. I don't use a buzzer in my setup, so I haven't really messed around with it

**Comment by camsaway** [comment]
Ok, Thanks. I'll take a look around and see what I can work out (absolute Pi and Python newbie but I'm sure I can work it out - I'll look from some other code where he calls an Actor and see what I come up with).
